import Head from 'next/head';
// import Image from 'next/image';
// import styles from '../styles/Home.module.css';
import Feed from "../components/Feed";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Reels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*  <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome Pepcoders
        </h1> 
      </main> */}
      <Feed/>
    </div>
  );
}
